server:
  port: 8074
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: form-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      uri: mongodb://administrator:get2Busw4frlxas6uCHek7pru2ac3uwlqoswapr9sWafu8r4v57Ud0h49oboBrom@localhost:27017/marketplace?authSource=admin
  security:
    user:
      password: Abcd@1234$
      name: member
    basic:
      enabled: true
      authorize-mode: NONE
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssbcapital.noreply@gmail.com
    password: jmoydmgyvqtjnhpa
  application:
    name: marketplace-ms
  storage:
    location: /files-storage
springdoc:
  api-docs:
    path: /swagger-doc/v3/api-docs
  #    enabled: true
  #    enabled: true
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
#    enabled: true
#    filter: true
#    tagsSorter: true
#    operationsSorter: true
#  show-actuator: true
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:cR1bIYuphisplregicrlqUbucHAdruRLCaSiSwAslbOrabrubitOPhustetH88In@localhost:8761/eureka

app:
  jwt-secret: "daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb"
  jwt-expiration-milliseconds: 604800000
  client:
    base-url: http://localhost:4200/
  openapi:
    dev-url: http://localhost:8074
    prod-url: https://bezkoder-api.com
  attachment:
    invoice: path_to_file
  mail:
    system:
      sender: ssbcapital.noreply@gmail.com
    templates:
      path: mail-templates
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              MongoOperations: DEBUG
    mongodb:
      driver: DEBUG
    com:
      hyperform:
        application:
          formbuilder:
            configuration:
              MongoLoggingConfig: DEBUG
